// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjmy75kqBK24CdSopdlyla-Kh1w0xkAg',
    appId: '1:516957124706:android:e2f385a9df3b36a35fb93b',
    messagingSenderId: '516957124706',
    projectId: 'mobileappdev-92920',
    storageBucket: 'mobileappdev-92920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVCUJY-vCfs19C0jPmMfaRk5y8NO4eBY',
    appId: '1:516957124706:ios:b9eadcd7d90535fb5fb93b',
    messagingSenderId: '516957124706',
    projectId: 'mobileappdev-92920',
    storageBucket: 'mobileappdev-92920.appspot.com',
    iosClientId: '516957124706-eh3mpeavb4cvnc2tajrj66k5g8b6dv05.apps.googleusercontent.com',
    iosBundleId: 'com.aav.mobileAppDev',
  );
}
